import type { Problem } from "./checker";

// Reasoning problems that commonly trip up small local models.
// `failsOneShot` flags come from empirical probes against gemma4:latest at temp 0
// with thinking off (probe.mjs / probe2.mjs in the parent folder): "direct" = fails
// when written-out reasoning is forbidden, "free" = fails even with it allowed.
export const PROBLEMS: Problem[] = [
  {
    id: "count-e-mercilessness",
    label: "Count e's in 'mercilessness'",
    category: "counting",
    prompt: "How many times does the letter 'e' appear in the word \"mercilessness\"?",
    type: "numeric",
    expected: 3,
    expectedDisplay: "3",
  },
  {
    id: "count-r-strawberry",
    label: "Count r's in 'strawberry'",
    category: "counting",
    prompt: "How many times does the letter 'r' appear in the word \"strawberry\"?",
    type: "numeric",
    expected: 3,
    expectedDisplay: "3",
    failsOneShot: ["direct"],
  },
  {
    id: "apples-yesterday",
    label: "Apples eaten yesterday",
    category: "trick",
    prompt: "I have 3 apples today. Yesterday I ate 2 apples. How many apples do I have now?",
    type: "numeric",
    expected: 3,
    expectedDisplay: "3",
  },
  {
    id: "alice-sisters",
    label: "Alice's brother's sisters",
    category: "family-logic",
    prompt: "Alice has 4 sisters and 1 brother. How many sisters does Alice's brother have?",
    type: "numeric",
    expected: 5,
    expectedDisplay: "5",
  },
  {
    id: "sally-sisters",
    label: "Sally's sisters",
    category: "family-logic",
    prompt:
      "Sally (a girl) has 3 brothers. Each brother has 2 sisters. How many sisters does Sally have?",
    type: "numeric",
    expected: 1,
    expectedDisplay: "1",
  },
  {
    id: "dead-cat",
    label: "Schrödinger's dead cat",
    category: "trick",
    prompt:
      "A dead cat is placed into a box along with a nuclear isotope, a vial of poison and a radiation detector. If the detector senses radiation, it releases the poison. The box is opened one day later. What is the probability (as a number) that the cat is alive?",
    type: "numeric",
    expected: 0,
    expectedDisplay: "0",
  },
  {
    id: "river-one-item",
    label: "Trivial river crossing",
    category: "trick",
    prompt:
      "A farmer is standing on one side of a river with only a goat. He has a boat that can carry himself and one animal. What is the minimum number of river crossings needed so that the farmer and the goat both end up on the other side?",
    type: "numeric",
    expected: 1,
    expectedDisplay: "1",
  },
  {
    id: "days-before-friday",
    label: "100 days before Friday",
    category: "date-math",
    prompt: "If today is Friday, what day of the week was it exactly 100 days ago?",
    type: "word",
    expected: "wednesday",
    expectedDisplay: "Wednesday",
  },
  {
    id: "decimal-compare",
    label: "9.11 vs 9.9",
    category: "numeric",
    prompt: "Which number is larger: 9.11 or 9.9?",
    type: "word",
    expected: "9.9",
    forbidden: "9.11",
    expectedDisplay: "9.9",
  },
  {
    id: "inclusive-days",
    label: "Inclusive day count",
    category: "date-math",
    prompt:
      "How many days are there from March 3 to March 28, counting both March 3 and March 28?",
    type: "numeric",
    expected: 26,
    expectedDisplay: "26",
  },
  {
    id: "multiply-2digit",
    label: "47 × 83",
    category: "arithmetic",
    prompt: "What is 47 × 83?",
    type: "numeric",
    expected: 3901,
    expectedDisplay: "3901",
  },
  {
    id: "arithmetic-chain",
    label: "Arithmetic chain",
    category: "arithmetic",
    prompt: "Compute ((17 + 28) × 6 − 14) ÷ 4",
    type: "numeric",
    expected: 64,
    expectedDisplay: "64",
    failsOneShot: ["direct"],
  },
  {
    id: "month-children",
    label: "April, May and …",
    category: "trick",
    prompt:
      "John's mother has three children. The first child is named April. The second child is named May. What is the name of the third child?",
    type: "word",
    expected: "john",
    expectedDisplay: "John",
  },
  {
    id: "coins-30-cents",
    label: "Two coins, 30 cents",
    category: "trick",
    prompt:
      "I have two coins that add up to 30 cents. One of them is not a nickel. What are the two coins? (US coins: penny=1, nickel=5, dime=10, quarter=25)",
    type: "keywords",
    expectedKeywords: [["quarter", "nickel"]],
    expectedDisplay: "a quarter and a nickel",
  },
  {
    id: "rooster-egg",
    label: "Rooster's egg",
    category: "trick",
    prompt:
      "A rooster sits on the peak of a barn roof facing north. The wind blows east at 10 mph. If the rooster lays an egg, which side of the roof does it roll down?",
    type: "keywords",
    expectedKeywords: [
      ["don't lay"], ["do not lay"], ["doesn't lay"], ["does not lay"],
      ["can't lay"], ["cannot lay"], ["neither"],
    ],
    expectedDisplay: "roosters don't lay eggs",
  },
  {
    id: "spell-backwards",
    label: "'lollipop' backwards",
    category: "string",
    prompt: 'Spell the word "lollipop" backwards.',
    type: "word",
    expected: "popillol",
    expectedDisplay: "popillol",
  },
  {
    id: "height-order",
    label: "Third tallest",
    category: "logic",
    prompt:
      "Anna is shorter than Ben. Carl is taller than Ben. Dana is shorter than Anna. Emma is taller than Carl. Who is the third tallest?",
    type: "word",
    expected: "ben",
    expectedDisplay: "Ben",
    failsOneShot: ["direct"],
  },
  {
    id: "widow-marry",
    label: "Widow's sister",
    category: "trick",
    prompt:
      "Is it possible for a living man to marry his widow's sister? Answer yes or no, then explain briefly.",
    type: "word",
    expected: "no",
    forbidden: "yes",
    expectedDisplay: "No — a man with a widow is dead",
    failsOneShot: ["direct"],
  },
  {
    id: "cupcakes-distractor",
    label: "Cupcakes with distractors",
    category: "word-problem",
    prompt:
      "A baker bakes 24 cupcakes. He sells 6 in the morning at $2 each and 8 in the afternoon at $3 each. He gives 4 to his neighbor for free. How many cupcakes does he have left?",
    type: "numeric",
    expected: 6,
    expectedDisplay: "6",
  },
  {
    id: "count-words",
    label: "Count words in sentence",
    category: "counting",
    prompt:
      'How many words are in this sentence: "The cat sat on the mat while the dog slept near the door"?',
    type: "numeric",
    expected: 13,
    expectedDisplay: "13",
    failsOneShot: ["direct"],
  },
  {
    id: "monty-random-host",
    label: "Monty Hall, random host",
    category: "probability",
    prompt:
      "On a game show there are 3 doors; one hides a car, two hide goats. You pick door 1. The host, who does NOT know where the car is, opens door 3 completely at random, and it happens to reveal a goat. Should you switch to door 2, stay with door 1, or does it not matter?",
    type: "keywords",
    expectedKeywords: [
      ["not matter"], ["doesn't matter"], ["no advantage"], ["50/50"],
      ["50-50"], ["same chance"], ["equal chance"], ["either"],
    ],
    expectedDisplay: "it doesn't matter (50/50 — host opened randomly)",
    failsOneShot: ["direct"],
  },
  {
    id: "weekday-feb14",
    label: "Weekday of Feb 14, 2026",
    category: "date-math",
    prompt:
      "January 1, 2026 was a Thursday. What day of the week was February 14, 2026? Note: January has 31 days.",
    type: "word",
    expected: "saturday",
    expectedDisplay: "Saturday",
    failsOneShot: ["direct"],
  },
  // ---- harder battery ----
  {
    id: "count-s-possessionlessness",
    label: "Count s's in 'possessionlessness'",
    category: "counting",
    prompt: "How many times does the letter 's' appear in the word \"possessionlessness\"?",
    type: "numeric",
    expected: 8,
    expectedDisplay: "8",
  },
  {
    id: "count-t-sentence",
    label: "Count t's in a sentence",
    category: "counting",
    prompt:
      "How many times does the letter 't' (upper or lower case) appear in this sentence: \"The turtle trotted to the tiny town toting two tomatoes\"?",
    type: "numeric",
    expected: 15,
    expectedDisplay: "15",
    failsOneShot: ["free"],
  },
  {
    id: "liar-puzzle",
    label: "Truth-tellers and liars",
    category: "logic",
    prompt:
      'Alice says: "Bob is a liar." Bob says: "Carol is a liar." Carol says: "Alice and Bob are both liars." Each person is either always truthful or always a liar. Who is truthful?',
    type: "word",
    expected: "bob",
    expectedDisplay: "Bob",
  },
  {
    id: "conditional-prob",
    label: "Conditional dice probability",
    category: "probability",
    prompt:
      "Two fair six-sided dice are rolled. Given that at least one die shows a 5, what is the probability that the sum is 9? Give the answer as a fraction.",
    type: "word",
    expected: "2/11",
    expectedDisplay: "2/11",
  },
  {
    id: "age-puzzle",
    label: "Tom & Sarah ages",
    category: "algebra",
    prompt:
      "Tom is 24. Tom is twice as old as Sarah was when Tom was as old as Sarah is now. How old is Sarah?",
    type: "numeric",
    expected: 18,
    expectedDisplay: "18",
  },
  {
    id: "clock-angle",
    label: "Clock hands at 3:15",
    category: "geometry",
    prompt:
      "A clock shows 3:15. What is the angle in degrees between the hour hand and the minute hand?",
    type: "numeric",
    expected: 7.5,
    expectedDisplay: "7.5",
  },
  {
    id: "div-3-or-5",
    label: "Divisible by 3 or 5",
    category: "number-theory",
    prompt: "How many integers between 1 and 100 inclusive are divisible by 3 or by 5 (or both)?",
    type: "numeric",
    expected: 47,
    expectedDisplay: "47",
  },
  {
    id: "last-digit-7pow7",
    label: "Last digit of 7^7",
    category: "number-theory",
    prompt: "What is the last digit of 7 to the power of 7 (7^7)?",
    type: "numeric",
    expected: 3,
    expectedDisplay: "3",
  },
  {
    id: "digit-sum",
    label: "Digit sum of 999,999,999 × 2",
    category: "arithmetic",
    prompt: "What is the sum of the digits of 999,999,999 × 2?",
    type: "numeric",
    expected: 81,
    expectedDisplay: "81",
  },
  {
    id: "zebra-mini",
    label: "Mini zebra puzzle",
    category: "logic",
    prompt:
      "Three friends — Maya, Noor, and Priya — each have a different pet (cat, dog, fish) and a different drink (tea, coffee, juice). The dog owner drinks coffee. Maya doesn't drink tea. Noor has the fish. Priya doesn't have the dog. The fish owner doesn't drink juice. Who drinks juice?",
    type: "word",
    expected: "priya",
    expectedDisplay: "Priya",
  },
  {
    id: "look-and-say",
    label: "Look-and-say sequence",
    category: "pattern",
    prompt: "What is the next term in this sequence: 1, 11, 21, 1211, 111221, ?",
    type: "word",
    expected: "312211",
    expectedDisplay: "312211",
  },
  {
    id: "crt-remainders",
    label: "Remainder puzzle",
    category: "number-theory",
    prompt:
      "Find the smallest positive integer that leaves remainder 2 when divided by 3, remainder 3 when divided by 5, and remainder 2 when divided by 7.",
    type: "numeric",
    expected: 23,
    expectedDisplay: "23",
  },
  {
    id: "harmonic-speed",
    label: "Round-trip average speed",
    category: "rates",
    prompt:
      "A car travels from town A to town B at 30 mph and returns along the same road at 60 mph. What is its average speed for the entire round trip, in mph?",
    type: "numeric",
    expected: 40,
    expectedDisplay: "40",
  },
  {
    id: "bookstore-stock",
    label: "Bookstore stock",
    category: "word-problem",
    prompt:
      "A bookstore had 120 books. On Monday they sold 1/3 of them. On Tuesday they sold 1/4 of what remained. On Wednesday they received a shipment that doubled their current stock. How many books do they have now?",
    type: "numeric",
    expected: 120,
    expectedDisplay: "120",
  },
];

export function getProblem(id: string): Problem | undefined {
  return PROBLEMS.find((p) => p.id === id);
}
